name: Deploy to Git Pages
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - release
jobs:
  publish:
    runs-on: [native-x86_64-linux, bigger-parallel]
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: Build and push
        env:
          TARGET_SITE: ${{ github.ref_name == 'release' && 'https://nix-vert.bartoostveen.nl' || 'https://test.nix-vert.bartoostveen.nl' }}
        run: |
          nix build .#_docs -L --accept-flake-config
          nix run nixpkgs#git-pages-cli -- \
            "$TARGET_SITE" \
            --parents \
            --token=${{ forge.token }} \
            --upload-dir=result/
  release-pr:
    if: github.ref_name == 'master'
    runs-on: gpg

    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: Create release PR
        run: |
          set -euo pipefail

          base="release"
          head="master"

          existing_prs="$(
            curl --silent --fail-with-body \
              -H "Authorization: token $FORGEJO_TOKEN" \
              "$FORGEJO_SERVER_URL/api/v1/repos/$FORGEJO_REPOSITORY/pulls?state=open"
          )"

          if jq -e --arg head "$head" 'any(.[]; .head.ref == $head)' <<< "$existing_prs" > /dev/null; then
            echo "PR for branch '$head' already exists, exiting."
            exit 0
          fi

          title="chore: update release"
          pr_body="Updates production to the latest changes in testing. Preview: https://test.nix-vert.bartoostveen.nl"

          jq -n \
            --arg base "$base" \
            --arg head "$head" \
            --arg title "$title" \
            --arg body "$pr_body" \
            '{
              base: $base,
              head: $head,
              title: $title,
              body: $body
            }' |
          curl --fail-with-body "$FORGEJO_SERVER_URL/api/v1/repos/$FORGEJO_REPOSITORY/pulls" \
            -H "Authorization: token $FORGEJO_TOKEN" \
            -H "Content-Type: application/json" \
            --data @-
